config/routes.rb
ConeyIslandScoreboard::Application.routes.draw do
  resources :scores

    root to: 'scores#index'

end

app/models/score.rb
class Score < ActiveRecord::Base

	validates_presence_of :name, :hole1, :hole2, :hole3

  	validates_numericality_of :hole1, :only_integer => true, :greater_than => 0
  	validates_numericality_of :hole2, :only_integer => true, :greater_than => 0
  	validates_numericality_of :hole3, :only_integer => true, :greater_than => 0

	
	scope :by_score, order('hole1+hole2+hole3')



  	def total_score
  		return self.hole1 + self.hole2 + self.hole3
  	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.by_score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to :back, notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :hole1, :hole2, :hole3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConeyIslandScoreboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

		<%= yield %>

</body>
</html>

app/views/scores/_form.html.erb
</br>
<%= simple_form_for(@score) do |f| %>
  <%= f.input :name %>
  <%= f.input :hole1 %>
  <%= f.input :hole2 %>
  <%= f.input :hole3 %>
</br>
  <%= f.button :submit, "Create", class: 'btn btn-primary' %>
</br>
</br>
<% end %>

app/views/scores/_scoreboard.html.erb
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Hole 1</th>
          <th>Hole 2</th>
          <th>Hole 3</th>
          <th>Total Score</th>
        </tr>
      </thead>

      <tbody class = "table-striped">
        <% @scores.each do |score| %>
          <tr>
            <td><%= score.name %></td>
            <td><%= score.hole1 %></td>
            <td><%= score.hole2 %></td>
            <td><%= score.hole3 %></td>
            <td><%= score.total_score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<div class = "container">
  <div class="table-responsive">
    <table class="table">
      
      <div id="refill-me">
        <tbody class = "table-striped">
          <% @scores[0,10].each do |score| %>
            <tr class="<%= cycle("even", "odd") %>">
              <td width="32%"><%= score.name %></td>
              <td width="23%"><%= score.hole1 %></td>
              <td width="15%"><%= score.hole2 %></td>
              <td width="15%"><%= score.hole3 %></td>
              <td width="15%"><%= score.total_score %></td>
            </tr>
          <% end %>
        </tbody>
      </div><!-- end refill me -->
    </table>
  </div>
</div>

<br>

<%= link_to 'New Score', new_score_path %>

<%= javascript_tag do %>
$(document).ready(function() {
        // Refreshes the page every 5 seconds
        //setTimeout(function(){window.location.reload(1);}, 5000);
        
  $(function() {
    startRefresh();
  });

  function startRefresh() {
      setTimeout(startRefresh,5000);
      $.get('/', function(data) {


          var newtable = $(data).find('.table-striped');
          $('.table-striped').replaceWith(newtable);    
          console.log(newtable.html());
      });
  }      

});
<% end %>

app/views/scores/new.html.erb
<center><h1>New Score</h1></center>

<div class = "container">

<%= render 'form' %>

</div>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score.name %>
</p>

<p>
  <strong>Hole1:</strong>
  <%= @score.hole1 %>
</p>

<p>
  <strong>Hole2:</strong>
  <%= @score.hole2 %>
</p>

<p>
  <strong>Hole3:</strong>
  <%= @score.hole3 %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>